LIBS = `pkg-config --libs opencv`
GPP = g++ -ggdb

colourthr: colourthr.cpp
	$(GPP) -o colourthr.exe colourthr.cpp $(LIBS)

convolution: convolution.cpp
	$(GPP) -o convolution.exe convolution.cpp $(LIBS)

revert0: revert0.cpp
	$(GPP) -o revert0.exe revert0.cpp $(LIBS)

revert1: revert1.cpp
	$(GPP) -o revert1.exe revert1.cpp $(LIBS)

revert2: revert2.cpp
	$(GPP) -o revert2.exe revert2.cpp $(LIBS)

revert3: revert3.cpp
	$(GPP) -o revert3.exe revert3.cpp $(LIBS)

RGBtoHSV: RGBtoHSV.cpp
	$(GPP) -o RGBtoHSV.exe RGBtoHSV.cpp $(LIBS)
